### ISSUE TITLE
[PE-D][Tester B] Manually editing the file with invalid data deletes all data

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T15-4/tp#172]
Expected Response:
The application displays an error of some sort telling the user that the data is corrupted.

Actual Response:
The .json file is wiped clean and all data is lost.

![image.png](https://raw.githubusercontent.com/deeyonn/ped/main/files/39b76001-07c5-431c-b7fc-89575100d057.png)

This could also be an issue where the application is trying to load an exercise with a very long name in relation to Issue #3.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: deeyonn/ped#5

**Comment by ErvinK123** [comment]
Added a warning in the UG.
